# netlify.toml

[build]
  publish = "."
  # Run the Node.js script to inject environment variables
  command = "npm install && npm run netlify-build"

# You still need to define these variables in Netlify UI under Site settings > Build & deploy > Environment variables
# The values below are dummy placeholders; actual values come from the Netlify UI.
[context.production.environment]
  VUE_APP_FIREBASE_API_KEY = "dummy_key" # Keep these as dummy values in the file
  VUE_APP_FIREBASE_AUTH_DOMAIN = "dummy_auth_domain"
  VUE_APP_FIREBASE_PROJECT_ID = "dummy_project_id"
  VUE_APP_FIREBASE_STORAGE_BUCKET = "dummy_storage_bucket"
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID = "dummy_messaging_sender_id"
  VUE_APP_FIREBASE_APP_ID = "dummy_app_id"