# netlify.toml

[build]
  publish = "."
  # Run the Node.js script to inject environment variables
  command = "npm install && npm run netlify-build"

# You still need to define these variables in Netlify UI under Site settings > Build & deploy > Environment variables
# The values below are dummy placeholders; actual values come from the Netlify UI.